apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  labels:
    app: mongo
  namespace: default
  annotations:
    description: "MongoDB root credentials"
type: Opaque
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: cGFzc3dvcmQ= 